# This file was generated by GoReleaser. DO NOT EDIT.
cask "shiplog" do
  name "shiplog"
  desc "Export Claude Code sessions to beautiful, shareable HTML chat logs"
  homepage "https://github.com/HabibPro1999/shiplog"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shiplog"

  on_macos do
    on_intel do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_darwin_amd64.tar.gz"
      sha256 "882114e20440f0f5fa537274f7ac14b966826d8acd29dba2707d605236cf59be"
    end
    on_arm do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_darwin_arm64.tar.gz"
      sha256 "a157ce0ce9f28386f72bbbf4c0ee50429ed5ee8b943799ec34da916b337b2e6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_linux_amd64.tar.gz"
      sha256 "01b33f8b3c5e9d003fb34c611c798772f88c22861b298f645cc67088ecc72612"
    end
    on_arm do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_linux_arm64.tar.gz"
      sha256 "2d36bfe574ae132ac940846af56e913558922fb476ea3419dda121e995f723ef"
    end
  end

  # No zap stanza required
end
