# This file was generated by GoReleaser. DO NOT EDIT.
cask "shiplog" do
  name "shiplog"
  desc "Export Claude Code sessions to beautiful, shareable HTML chat logs"
  homepage "https://github.com/HabibPro1999/shiplog"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shiplog"

  on_macos do
    on_intel do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_darwin_amd64.tar.gz"
      sha256 "870fe0da505095e36642ad2a0833d074fa163527e071a8fd61d46e93597910d2"
    end
    on_arm do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_darwin_arm64.tar.gz"
      sha256 "5c3c709be894476abbae4ad97581c3778a85a35aa72f7f6c93d8c93101a3d746"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_linux_amd64.tar.gz"
      sha256 "698f8e458f75f2663ed7faf7bd69645eb7dbe156a79ca35af2915191aab4cbd7"
    end
    on_arm do
      url "https://github.com/HabibPro1999/shiplog/releases/download/v#{version}/shiplog_linux_arm64.tar.gz"
      sha256 "c9b98756b02c72d03dc37230c0ca031231d41d4a0b4f00af47181a616fa33fa3"
    end
  end

  # No zap stanza required
end
